"""update fk cascade

Revision ID: 48bf650c7f7e
Revises: 8048eb5ed7ef
Create Date: 2026-05-18 23:18:53.086693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48bf650c7f7e'
down_revision: Union[str, Sequence[str], None] = '8048eb5ed7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('price_history_product_id_fkey'), 'price_history', type_='foreignkey')
    op.create_foreign_key(None, 'price_history', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_history', type_='foreignkey')
    op.create_foreign_key(op.f('price_history_product_id_fkey'), 'price_history', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
